declare module 'quasar/src/vue-plugin.js'
declare module 'quasar/lang/nl'
declare module 'quasar/src/components/input'
declare module 'quasar/src/components/select'
declare module 'quasar/src/components/checkbox'
